// UI copy (pt-BR) for the company registry screens (T6). All user-facing strings
// live here — never inline in JSX.
export const copy = {
  list: {
    title: 'Empresas',
    subtitle: 'Carteira de clientes do escritório.',
    newCompany: 'Nova empresa',
    filters: 'Filtros',
    searchLabel: 'Buscar',
    searchPlaceholder: 'Razão social ou nome fantasia',
    statusLabel: 'Situação',
    statusActive: 'Ativas',
    statusArchived: 'Arquivadas',
    statusAll: 'Todas',
    apply: 'Aplicar',
    importCompanies: 'Importar planilha',
    regimeUnset: 'Regime não informado',
    badgeArchived: 'Arquivada',
    empty: {
      title: 'Nenhuma empresa cadastrada',
      description: 'Cadastre a primeira empresa da carteira para começar.',
      filteredTitle: 'Nenhuma empresa encontrada',
      filteredDescription: 'Ajuste a busca ou a situação e tente de novo.',
    },
  },
  form: {
    newTitle: 'Nova empresa',
    newSubtitle: 'Digite o CNPJ — buscamos os dados oficiais e você só revisa.',
    editTitle: 'Editar empresa',
    editSubtitle: 'O CNPJ não pode ser alterado — ele identifica a empresa.',
    cnpj: 'CNPJ',
    cnpjInvalid: 'CNPJ inválido — verifique os dígitos.',
    lookup: 'Buscar dados do CNPJ',
    lookingUp: 'Buscando na Receita…',
    lookupHint: 'Razão social, endereço, CNAE e sócios vêm preenchidos automaticamente.',
    lookupFailed: 'Não foi possível buscar os dados agora — preencha manualmente.',
    lookupDone: 'Dados preenchidos automaticamente. Revise e salve.',
    manualFill: 'Preencher manualmente',
    changeCnpj: 'Trocar',
    legalName: 'Razão social',
    tradeName: 'Nome fantasia',
    taxRegime: 'Regime fiscal',
    taxRegimeNone: 'Não informado',
    city: 'Cidade',
    state: 'UF',
    optional: '(opcional)',
    detailsSection: 'Dados adicionais (opcionais)',
    addressSection: 'Endereço (opcional)',
    legalNature: 'Natureza jurídica',
    companySize: 'Enquadramento (porte)',
    stateRegistration: 'Inscrição estadual',
    municipalRegistration: 'Inscrição municipal',
    nire: 'NIRE',
    nireIssuedOn: 'Data do NIRE',
    activitiesStartedOn: 'Início das atividades',
    serviceStartedOn: 'Início da prestação de serviço',
    shareCapital: 'Capital social (R$)',
    cnaeCode: 'CNAE principal',
    cnaeDescription: 'Descrição do CNAE',
    addressStreet: 'Logradouro',
    addressNumber: 'Número',
    addressComplement: 'Complemento',
    addressDistrict: 'Bairro',
    addressZip: 'CEP',
    partnersFound: (n: number) =>
      n === 1 ? '1 sócio encontrado — será cadastrado junto.' : `${n} sócios encontrados — serão cadastrados juntos.`,
    submitNew: 'Cadastrar empresa',
    submitEdit: 'Salvar alterações',
    submitting: 'Salvando…',
    cancel: 'Cancelar',
  },
  detail: {
    backToList: 'Empresas',
    edit: 'Editar',
    archive: 'Arquivar',
    restore: 'Restaurar',
    archiveConfirm: 'Arquivar esta empresa? Ela sai da lista de empresas ativas.',
    restoreConfirm: 'Restaurar esta empresa para a lista de ativas?',
    working: 'Aguarde…',
    badgeActive: 'Ativa',
    badgeArchived: 'Arquivada',
    soon: 'Disponível em breve.',
    openRepository: 'Abrir repositório',
    documentsEmpty: 'Nenhum documento desta empresa ainda.',
    documentsEmptyHint: 'Envie arquivos pelo repositório — eles aparecem aqui organizados.',
    tabs: {
      dados: 'Dados',
      contatos: 'Contatos',
      tarefas: 'Tarefas',
      documentos: 'Documentos',
      prazos: 'Prazos',
      solicitacoes: 'Solicitações',
      regras: 'Regras',
    },
    fields: {
      cnpj: 'CNPJ',
      legalName: 'Razão social',
      tradeName: 'Nome fantasia',
      taxRegime: 'Regime fiscal',
      location: 'Cidade / UF',
      legalNature: 'Natureza jurídica',
      companySize: 'Enquadramento',
      stateRegistration: 'Inscrição estadual',
      municipalRegistration: 'Inscrição municipal',
      nire: 'NIRE',
      activitiesStartedOn: 'Início das atividades',
      serviceStartedOn: 'Início da prestação',
      address: 'Endereço',
      shareCapital: 'Capital social',
      cnae: 'CNAE principal',
      unset: '—',
    },
    moreData: 'Mais dados cadastrais',
  },
  partners: {
    title: 'Sócios',
    add: 'Adicionar sócio',
    name: 'Nome',
    cpfCnpj: 'CPF/CNPJ',
    qualification: 'Qualificação',
    ownershipPercent: 'Participação (%)',
    joinedOn: 'Entrada na sociedade',
    save: 'Salvar',
    saving: 'Salvando…',
    cancel: 'Cancelar',
    edit: 'Editar',
    remove: 'Remover',
    removeConfirm: 'Remover este sócio?',
    empty: 'Nenhum sócio cadastrado.',
    emptyHint: 'Os sócios vêm do quadro societário (QSA) na busca por CNPJ, ou adicione manualmente.',
  },
  enrichment: {
    title: 'Dados oficiais (Receita Federal)',
    enrich: 'Enriquecer',
    enriching: 'Buscando…',
    pending: 'Enriquecendo pelo CNPJ — atualize a página em instantes.',
    none: 'Ainda não enriquecido. Buscamos razão social, CNAE e endereço pelo CNPJ.',
    legalName: 'Razão social (oficial)',
    cnae: 'CNAE principal',
    registration: 'Situação cadastral',
    address: 'Endereço',
  },
  import: {
    title: 'Importar empresas',
    subtitle: 'Suba uma planilha (.csv ou .xlsx) para cadastrar várias empresas de uma vez.',
    fileLabel: 'Planilha',
    template: 'Baixar modelo',
    templateHint:
      'Baixe o modelo para garantir as colunas certas (CNPJ e Razão Social são obrigatórios).',
    analyze: 'Analisar planilha',
    analyzing: 'Analisando…',
    noFile: 'Escolha um arquivo .csv ou .xlsx primeiro.',
    previewTitle: 'Confira antes de importar',
    countValid: 'prontas',
    countDuplicate: 'duplicadas',
    countInvalid: 'com erro',
    back: 'Voltar',
    confirm: 'Importar',
    confirming: 'Importando…',
    nothingValid: 'Nenhuma linha pronta. Corrija os erros na planilha e analise de novo.',
    line: 'Linha',
    statusValid: 'Pronta',
    statusInvalid: 'Erro',
    statusDuplicate: 'Duplicada',
    doneTitle: 'Importação concluída',
    created: 'empresas importadas',
    skipped: 'linhas ignoradas (erros ou duplicadas)',
    enrichNote: 'O enriquecimento dos CNPJs roda em segundo plano.',
    goToList: 'Ver empresas',
    importMore: 'Importar outra',
  },
  prazos: {
    title: 'Prazos monitorados',
    add: 'Adicionar prazo',
    empty: 'Nenhum prazo monitorado.',
    emptyHint: 'Acompanhe certidões e licenças com vencimento — o farol acende sozinho.',
    kind: 'Tipo',
    dueDate: 'Vencimento',
    triggerDays: 'Alertar (dias antes)',
    noDueDate: 'Sem data',
    document: 'Documento vinculado (opcional)',
    documentNone: 'Nenhum',
    save: 'Salvar',
    saving: 'Salvando…',
    cancel: 'Cancelar',
    edit: 'Editar',
    remove: 'Remover',
    removeConfirm: 'Remover este prazo?',
    status: {
      no_date: 'Sem data',
      valid: 'Em dia',
      due_soon: 'Vence em breve',
      overdue: 'Vencido',
      needs_update: 'Revisar',
    } as Record<string, string>,
  },
  solicitacoes: {
    add: 'Nova solicitação',
    empty: 'Nenhuma solicitação.',
    emptyHint: 'Peça um documento ao cliente ou disponibilize um arquivo por link seguro.',
    kind: 'Tipo',
    kindUpload: 'Solicitar envio de documento',
    kindOffer: 'Disponibilizar documento',
    title: 'Título',
    titlePlaceholder: 'Ex.: Envie o contrato social atualizado',
    description: 'Mensagem ao cliente (opcional)',
    docType: 'Documento esperado (opcional)',
    docTypeAny: 'Qualquer documento',
    document: 'Documento a disponibilizar',
    documentPick: 'Selecione um documento…',
    noDocs: 'Esta empresa ainda não tem documentos para disponibilizar.',
    expiryDays: 'Validade do link (dias)',
    create: 'Gerar link',
    creating: 'Gerando…',
    cancel: 'Cancelar',
    cancelRequest: 'Cancelar',
    cancelConfirm: 'Cancelar esta solicitação? O link deixará de funcionar.',
    expiresIn: (days: number) =>
      days < 0
        ? 'link expirado'
        : days === 0
          ? 'expira hoje'
          : days === 1
            ? 'expira amanhã'
            : `expira em ${days} dias`,
    linkTitle: 'Link gerado',
    linkHint: 'Copie agora — por segurança, o link não é exibido novamente.',
    copy: 'Copiar link',
    copied: 'Copiado!',
    newAnother: 'Nova solicitação',
    status: {
      requested: 'Aguardando',
      sent: 'Enviado',
      viewed: 'Visualizado',
      received: 'Recebido',
      downloaded: 'Baixado',
      expired: 'Expirado',
      cancelled: 'Cancelado',
    } as Record<string, string>,
  },
  contacts: {
    add: 'Adicionar contato',
    name: 'Nome',
    email: 'E-mail',
    phone: 'Telefone',
    channel: 'Canal preferido',
    channels: { email: 'E-mail', phone: 'Telefone', whatsapp: 'WhatsApp' },
    departments: 'Departamentos que este contato atende',
    departmentsHint: 'Sem marcação = atende todos. Usado para sugerir o destinatário certo.',
    departmentsAll: 'Todos',
    primary: 'Principal',
    markPrimary: 'Marcar como contato principal',
    save: 'Salvar',
    saving: 'Salvando…',
    cancel: 'Cancelar',
    edit: 'Editar',
    remove: 'Remover',
    removeConfirm: 'Remover este contato?',
    empty: 'Nenhum contato cadastrado.',
    emptyHint: 'Adicione quem fala pelo cliente — quem recebe cobranças e solicitações.',
  },
} as const;

// Shared control classes, matching the settings screen.
export const inputClass =
  'w-full rounded-lg border bg-background px-3 py-2 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:opacity-60';
export const primaryButtonClass =
  'inline-flex items-center justify-center gap-1.5 rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90 disabled:opacity-60';
export const secondaryButtonClass =
  'inline-flex items-center justify-center gap-1.5 rounded-lg border px-4 py-2 text-sm font-medium transition-colors hover:bg-accent disabled:opacity-60';
