// UI copy (pt-BR) for the audit trail viewer (Configurações → Auditoria).

export const inputClass =
  'w-full rounded-lg border bg-background px-3 py-2 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring';

export const copy = {
  title: 'Auditoria',
  subtitle: 'Registro de quem fez o quê, e quando.',
  restricted: 'Apenas titulares e gestores podem ver a auditoria.',
  system: 'Sistema',
  filterLabel: 'Filtrar por tipo',
  filterAll: 'Tudo',
  empty: 'Nenhum evento registrado ainda.',
  drawer: {
    close: 'Fechar',
    who: 'Autor',
    when: 'Quando',
    entity: 'Item',
    entityId: 'ID do item',
    details: 'Detalhes',
    noDetails: 'Sem detalhes adicionais.',
  },
  // Entities that can appear + their pt-BR label (also drives the filter dropdown).
  entities: {
    company: 'Empresa',
    contact: 'Contato',
    task: 'Tarefa',
    document: 'Documento',
    exception: 'Exceção',
    document_request: 'Solicitação',
    support_ticket: 'Atendimento',
    export_batch: 'Exportação',
    monitored_document: 'Prazo',
    mapping_rule: 'Regra',
    firm: 'Configuração',
    user: 'Usuário',
  } as Record<string, string>,
  // Human label per audit action; unknown actions fall back to the raw string.
  actions: {
    'company.created': 'Empresa criada',
    'company.updated': 'Empresa atualizada',
    'company.archived': 'Empresa arquivada',
    'company.enriched': 'Empresa enriquecida',
    'company.enrichment_requested': 'Enriquecimento solicitado',
    'companies.imported': 'Empresas importadas',
    'contact.created': 'Contato criado',
    'contact.updated': 'Contato atualizado',
    'contact.deleted': 'Contato removido',
    'task.created': 'Tarefa criada',
    'task.status_changed': 'Status de tarefa alterado',
    'task.handed_off': 'Tarefa repassada',
    'recurring_task.created': 'Tarefa recorrente criada',
    'recurring_task.updated': 'Tarefa recorrente atualizada',
    'recurring_task.activated': 'Tarefa recorrente ativada',
    'document.created': 'Documento recebido',
    'document.deleted': 'Documento removido',
    'document.classified': 'Documento classificado (IA)',
    'document.cfop_applied': 'CFOP de entrada aplicado',
    'classification.corrected': 'Classificação corrigida',
    'triage.exception': 'Exceção de triagem',
    'exception.resolved': 'Exceção resolvida',
    'exception.ignored': 'Exceção ignorada',
    'rules.pending': 'Pendência de regra',
    'mapping_rule.created': 'Regra criada',
    'mapping_rule.updated': 'Regra atualizada',
    'mapping_rule.deleted': 'Regra removida',
    'monitored_document.created': 'Prazo criado',
    'monitored_document.updated': 'Prazo atualizado',
    'monitored_document.deleted': 'Prazo removido',
    'deadline.recomputed': 'Prazos recalculados',
    'request.created': 'Solicitação criada',
    'request.sent': 'Solicitação enviada',
    'request.reminded': 'Lembrete enviado',
    'request.cancelled': 'Solicitação cancelada',
    'export_batch.requested': 'Lote solicitado',
    'export_batch.built': 'Lote gerado',
    'export_batch.downloaded': 'Lote baixado',
    'support.received': 'Atendimento recebido',
    'support.ai_replied': 'Atendimento respondido pela IA',
    'support.replied': 'Atendimento respondido',
    'support.escalated': 'Atendimento encaminhado a humano',
    'support.resolved': 'Atendimento resolvido',
    'support.pending': 'Atendimento aguardando cliente',
    'support.open': 'Atendimento reaberto',
    'firm.config.updated': 'Configurações atualizadas',
    'user.created': 'Usuário criado',
    'user.role_changed': 'Papel de usuário alterado',
    'user.departments_set': 'Departamentos do usuário definidos',
    'user.removed': 'Usuário removido',
  } as Record<string, string>,
} as const;
