// UI copy (pt-BR) for the global request follow-up screen (T17).
export const copy = {
  title: 'Solicitações',
  subtitle: 'Acompanhe o que foi pedido aos clientes e reenvie quando precisar.',
  views: { open: 'Em aberto', all: 'Todas' },
  empty: {
    openTitle: 'Nenhuma solicitação em aberto',
    openHint: 'Tudo respondido por aqui ✅',
    allTitle: 'Nenhuma solicitação ainda',
    allHint: 'Crie uma solicitação na aba Solicitações de uma empresa.',
  },
  kindUpload: 'Envio solicitado',
  kindOffer: 'Documento disponibilizado',
  open: 'Abrir',
  close: 'Fechar',
  detail: {
    timeline: 'Histórico',
    noEvents: 'Sem interações ainda.',
    send: 'Enviar por e-mail',
    sending: 'Enviando…',
    sent: 'E-mail enviado ✅',
    emailLabel: 'E-mail do cliente',
    emailHint: 'Em branco = contato do departamento responsável (ou o principal).',
    noRecipient: 'Sem e-mail: informe um endereço ou cadastre um contato principal.',
    copy: 'Gerar e copiar novo link',
    copying: 'Gerando…',
    copied: 'Link copiado ✅',
    copyHint: 'Gera um link novo e invalida o anterior.',
    cancel: 'Cancelar solicitação',
    cancelConfirm: 'Cancelar esta solicitação? O link deixará de funcionar.',
  },
  events: {
    sent: 'Link enviado',
    viewed: 'Cliente abriu o link',
    received: 'Documento recebido',
    downloaded: 'Documento baixado',
    reminded: 'Lembrete enviado',
  } as Record<string, string>,
  status: {
    requested: 'Aguardando envio',
    sent: 'Enviado',
    viewed: 'Visualizado',
    received: 'Recebido',
    downloaded: 'Baixado',
    expired: 'Expirado',
    cancelled: 'Cancelado',
  } as Record<string, string>,
} as const;
