// UI copy (pt-BR) for the global request follow-up screen (T17/T31).
export const copy = {
  dialogBack: 'Voltar',
  title: 'Solicitações',
  subtitle: 'Pedidos de documentos e envios ao cliente, com histórico de cada link.',
  views: { open: 'Em aberto', all: 'Todas' },
  kindViews: { all: 'Tudo', upload: 'Solicitações', offer: 'Envios' },
  empty: {
    openTitle: 'Nada em aberto',
    openHint: 'Tudo respondido por aqui ✅',
    allTitle: 'Nenhuma solicitação ainda',
    allHint: 'Use "Nova solicitação" para pedir ou disponibilizar um documento.',
  },
  kindUpload: 'Envio solicitado',
  kindOffer: 'Documento disponibilizado',
  open: 'Abrir',
  close: 'Fechar',
  create: {
    button: 'Nova solicitação',
    title: 'Nova solicitação',
    subtitle: 'Peça um documento ao cliente ou disponibilize um arquivo por link seguro.',
    company: 'Empresa',
    companyPick: 'Escolha a empresa…',
    kind: 'Tipo',
    requestTitle: 'Título',
    titlePlaceholder: 'Ex.: Envie o contrato social atualizado',
    description: 'Mensagem (opcional)',
    docType: 'Documento esperado',
    docTypeAny: 'Qualquer documento',
    document: 'Documento a disponibilizar',
    documentPick: 'Escolha o documento…',
    noDocs: 'Esta empresa ainda não tem documentos no repositório para disponibilizar.',
    expiryDays: 'Validade do link (dias)',
    submit: 'Gerar link',
    creating: 'Gerando…',
    linkTitle: 'Link criado ✅',
    linkHint:
      'Copie agora — por segurança ele não aparece de novo. Para enviar por e-mail, abra a solicitação na lista.',
    copy: 'Copiar',
    copied: 'Copiado',
  },
  detail: {
    timeline: 'Histórico',
    loadingEvents: 'Carregando histórico…',
    noEvents: 'Sem interações ainda.',
    send: 'Enviar por e-mail',
    sending: 'Enviando…',
    sent: 'E-mail enviado ✅',
    sendTo: 'Enviar para',
    suggestedSuffix: ' · sugerido',
    otherEmail: 'Outro e-mail…',
    noContacts: 'Nenhum contato com e-mail nesta empresa — informe um endereço abaixo.',
    emailLabel: 'E-mail do destinatário',
    copy: 'Gerar e copiar novo link',
    copying: 'Gerando…',
    copied: 'Link copiado ✅',
    copyHint: 'Gera um link novo e invalida o anterior.',
    cancel: 'Cancelar solicitação',
    cancelTitle: 'Cancelar solicitação',
    cancelConfirm: 'Cancelar esta solicitação? O link deixará de funcionar.',
    cancelled: 'Solicitação cancelada.',
  },
  events: {
    sent: 'E-mail enviado',
    viewed: 'Cliente abriu o link',
    received: 'Documento recebido',
    downloaded: 'Documento baixado',
    reminded: 'Lembrete enviado',
    link_copied: 'Novo link gerado e copiado',
  } as Record<string, string>,
  status: {
    requested: 'Aguardando envio',
    sent: 'Enviado',
    viewed: 'Visualizado',
    received: 'Recebido',
    downloaded: 'Baixado',
    expired: 'Expirado',
    cancelled: 'Cancelado',
  } as Record<string, string>,
} as const;
