// UI copy (pt-BR) for the firm settings screen.
export const copy = {
  title: 'Configurações',
  subtitle: 'Parâmetros do escritório. Valem para todas as empresas.',
  deadlineLabel: 'Prazo de alerta padrão',
  deadlineSuffix: 'dias antes do vencimento',
  deadlineHint: 'Quantos dias antes do vencimento um prazo entra em alerta (amarelo).',
  aiLabel: 'Limite de confiança da triagem por IA',
  aiHint: 'Abaixo deste valor o documento vai para a fila de exceções. Entre 0 e 1.',
  supportTitle: 'Atendimento (dúvidas no WhatsApp)',
  supportAutoReplyLabel: 'Deixar a IA responder dúvidas simples',
  supportAutoReplyHint:
    'Quando ligado, a IA responde perguntas triviais com o contexto da empresa e encaminha o resto para um humano. Quando desligado, toda dúvida vai direto para a equipe.',
  supportThresholdLabel: 'Limite de confiança do atendimento por IA',
  supportThresholdHint:
    'Abaixo deste valor a IA não responde sozinha — encaminha para um humano. Entre 0 e 1.',
  save: 'Salvar',
  saving: 'Salvando…',
  saved: 'Configurações salvas.',
  readOnlyNote: 'Apenas titulares e gestores podem editar as configurações.',
  advanced: 'Opções avançadas',
  advancedNote: 'Para editar, abra "Configuração avançada" em Mais configurações.',
  departments: 'Departamentos',
  taxonomy: 'Tipos de documento',
  routing: 'Roteamento por tipo de documento',
  links: {
    title: 'Mais configurações',
    usersTitle: 'Usuários e permissões',
    usersDescription: 'Quem acessa o escritório, papéis e departamentos.',
    advancedTitle: 'Configuração avançada',
    advancedDescription: 'Departamentos, tipos de documento e roteamento da triagem.',
    auditTitle: 'Auditoria',
    auditDescription: 'Registro de quem fez o quê, e quando.',
    rulesTitle: 'Regras de CFOP',
    rulesDescription: 'De-para de CFOP de origem para CFOP de entrada, por fornecedor.',
    open: 'Abrir',
  },
} as const;
