// UI copy (pt-BR) for the firm settings screen.
export const copy = {
  title: 'Configurações',
  subtitle: 'Parâmetros do escritório. Valem para todas as empresas.',
  deadlineLabel: 'Prazo de alerta padrão',
  deadlineSuffix: 'dias antes do vencimento',
  deadlineHint: 'Quantos dias antes do vencimento um prazo entra em alerta (amarelo).',
  aiLabel: 'Confiança exigida da triagem por IA',
  aiHint: 'Documentos abaixo do nível escolhido vão para a fila de exceções, para revisão humana.',
  presets: {
    strict: (v: string) => `Rigoroso — quase tudo passa por revisão humana (${v})`,
    balanced: (v: string) => `Equilibrado — recomendado (${v})`,
    permissive: (v: string) => `Permissivo — a IA decide mais sozinha (${v})`,
    custom: 'Personalizado…',
    customLabel: 'Valor personalizado (entre 0 e 1)',
  },
  supportTitle: 'Atendimento (dúvidas no WhatsApp)',
  supportAutoReplyLabel: 'Deixar a IA responder dúvidas simples',
  supportAutoReplyHint:
    'Quando ligado, a IA responde perguntas triviais com o contexto da empresa e encaminha o resto para um humano. Quando desligado, toda dúvida vai direto para a equipe.',
  supportThresholdLabel: 'Confiança exigida do atendimento por IA',
  supportThresholdHint:
    'Abaixo do nível escolhido a IA não responde sozinha — encaminha para um humano.',
  supportModelLabel: 'Velocidade das respostas da IA',
  supportModelHint:
    'O modo rápido responde em poucos segundos e resolve bem dúvidas do dia a dia; os outros pensam mais, e demoram mais.',
  supportModelFast: 'Rápido — recomendado para conversa',
  supportModelBalanced: 'Intermediário',
  supportModelAdvanced: 'Avançado — máxima qualidade, mais lento',
  supportModelCurrent: (id: string) => `Atual (${id})`,
  supportFaqLabel: 'Respostas prontas (FAQ do escritório)',
  supportFaqPlaceholder: 'Qual o horário de atendimento? | De segunda a sexta, das 8h às 18h.',
  supportFaqHint:
    'Uma por linha, no formato "Pergunta | Resposta". A IA usa somente estas respostas e o contexto da empresa — nunca inventa políticas do escritório.',
  receptionTitle: 'Menu de recepção (WhatsApp)',
  receptionEnabledLabel: 'Receber novas conversas com o menu de departamentos',
  receptionEnabledHint:
    'O cliente escolhe um número e a conversa fica marcada com o departamento. "voltar" reabre o menu; "fim" encerra o atendimento.',
  receptionGreetingLabel: 'Mensagem de boas-vindas',
  receptionOptionsLabel: 'Opções do menu',
  receptionOptionsPlaceholder: '📊 Contabilidade | contabil\n👥 Departamento Pessoal | dp',
  receptionOptionsHint: (keys: string) =>
    `Uma opção por linha, no formato "Rótulo | departamento". Departamentos válidos: ${keys}.`,
  save: 'Salvar',
  saving: 'Salvando…',
  saved: 'Configurações salvas.',
  readOnlyNote: 'Apenas titulares e gestores podem editar as configurações.',
  advanced: 'Opções avançadas',
  advancedNote: 'Para editar, abra "Configuração avançada" em Mais configurações.',
  departments: 'Departamentos',
  taxonomy: 'Tipos de documento',
  routing: 'Roteamento por tipo de documento',
  links: {
    title: 'Mais configurações',
    usersTitle: 'Usuários e permissões',
    usersDescription: 'Quem acessa o escritório, papéis e departamentos.',
    advancedTitle: 'Configuração avançada',
    advancedDescription: 'Departamentos, tipos de documento e roteamento da triagem.',
    auditTitle: 'Auditoria',
    auditDescription: 'Registro de quem fez o quê, e quando.',
    rulesTitle: 'Regras de CFOP',
    rulesDescription: 'De-para de CFOP de origem para CFOP de entrada, por fornecedor.',
    open: 'Abrir',
  },
} as const;
